description: 'Sets up Node.js, PNPM, and caches dependencies'

inputs:
  install-deps:
    default: 'true'
    description: Whether to install dependencies
    required: false
  node-version:
    default: 24.7.0
    description: Node.js version
    required: false
  pnpm-version:
    default: 10.17.1
    description: PNPM version
    required: false
  registry-url:
    default: https://registry.npmjs.org
    description: Node package registry URL
    required: false
name: Setup Environment
runs:
  steps:
    - name: Setup PNPM
      uses: pnpm/action-setup@v4
      with:
        version: ${{ inputs.pnpm-version }}
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        cache: pnpm
        cache-dependency-path: pnpm-lock.yaml
        node-version: ${{ inputs.node-version }}
        registry-url: ${{ inputs.registry-url }}
    - if: ${{ inputs.install-deps == 'true' }}
      name: Install Dependencies
      run: pnpm i --frozen-lockfile
      shell: sh
  using: composite
