name: Changeset

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      force_deploy:
        default: false
        description: Force run all jobs
        required: false
        type: boolean

concurrency: ${{ github.workflow }}-${{ github.ref }}
env:
  NODE_VERSION: 24.7.0
  PNPM_VERSION: 10.17.1

jobs:
  install-dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v5
      - name: Setup environment
        uses: ./.github/actions/env-setup
        with:
          node-version: ${{ env.NODE_VERSION }}
          pnpm-version: ${{ env.PNPM_VERSION }}
  release:
    name: Release
    timeout-minutes: 15
    runs-on: ubuntu-latest
    needs: [install-dependencies]
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v4
      - name: Setup environment
        uses: ./.github/actions/env-setup
        with:
          node-version: ${{ env.NODE_VERSION }}
          pnpm-version: ${{ env.PNPM_VERSION }}
      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          commit: 'chore: update versions'
          title: 'chore: update versions'
          publish: pnpm ci:publish
          createGithubReleases: true
          commitMode: github-api
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
