name: Changeset

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      force_deploy:
        default: false
        description: Force run all jobs
        required: false
        type: boolean

concurrency: ${{ github.workflow }}-${{ github.ref }}
env:
  NODE_VERSION: 24.7.0
  PNPM_VERSION: 10.17.1

jobs:
  install-dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v5
      - name: Setup environment
        uses: ./.github/actions/env-setup
        with:
          node-version: ${{ env.NODE_VERSION }}
          pnpm-version: ${{ env.PNPM_VERSION }}
  release:
    name: Create or Update Release PR
    runs-on: ubuntu-latest
    needs: [install-dependencies]
    if: ${{ startsWith(github.ref, 'refs/tags/')  || github.event.inputs.force_deploy == true }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Create or Update Release Pull Request
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
