# This is a basic workflow to automatically build a Svelte app and deploy it to GitHub Pages
name: Publish to Production

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      force_deploy:
        default: false
        description: Force deploy all applications
        required: false
        type: boolean
        # Optional: Change the working directory
        # workingDirectory: my-site
        # Optional: Change the Wrangler version, allows you to point to a specific version or a tag such as `beta`

env:
  NODE_VERSION: 24.7.0
  PNPM_VERSION: 10.17.1

jobs:
  detect-changes:
    name: Detect Changes
    outputs:
      src: ${{ steps.path-filter.outputs.src }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - id: path-filter
        uses: ./.github/actions/path-filter
  install-dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v5
      - name: Setup environment
        uses: ./.github/actions/env-setup
        with:
          node-version: ${{ env.NODE_VERSION }}
          pnpm-version: ${{ env.PNPM_VERSION }}

  lint:
    name: Lint
    runs-on: ubuntu-latest
    if: ${{ needs.detect-changes.outputs.src == 'true' || github.event.inputs.force_deploy == true }}
    needs: [detect-changes, install-dependencies]
    steps:
      - name: Git Checkout
        uses: actions/checkout@v5
      - name: Setup environment
        uses: ./.github/actions/env-setup
        with:
          node-version: ${{ env.NODE_VERSION }}
          pnpm-version: ${{ env.PNPM_VERSION }}
      - name: Lint
        run: |
          pnpm lint
  test:
    name: tint
    runs-on: ubuntu-latest
    if: ${{ needs.detect-changes.outputs.src == 'true' || github.event.inputs.force_deploy == true }}
    needs: [detect-changes, install-dependencies]
    steps:
      - name: Git Checkout
        uses: actions/checkout@v5
      - name: Setup environment
        uses: ./.github/actions/env-setup
        with:
          node-version: ${{ env.NODE_VERSION }}
          pnpm-version: ${{ env.PNPM_VERSION }}
      - name: test
        run: |
          pnpm test
  publish-web-app:
    if: ${{ needs.detect-changes.outputs.src == 'true' || github.event.inputs.force_deploy == true }}
    name: Deploy Webapp
    needs: [detect-changes, install-dependencies]
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v5
      - name: Setup environment
        uses: ./.github/actions/env-setup
        with:
          node-version: ${{ env.NODE_VERSION }}
          pnpm-version: ${{ env.PNPM_VERSION }}
      - env:
          IS_CI: false
        name: Build
        run: |
          pnpm build
      - name: Publish Web App
        uses: cloudflare/pages-action@v1
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          # Optional: Switch what branch you are publishing to.
          # By default, this will be the branch which triggered this workflow
          branch: ${{ github.head_ref }}
          directory: ./.svelte-kit/cloudflare
          # Optional: Enable this if you want to have GitHub Deployments triggered
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          projectName: whatsin-fyi
